### ISSUE TITLE
SPB errors on Morelia

### ISSUE THREAD

**Issue by b-long** [Bioconductor/packagebuilder#13]
cc/ @jimhester 

As many of us have noticed, Morelia will print an error like this during a build : 

![screenshot from 2015-11-23 18 11 26](https://cloud.githubusercontent.com/assets/66993/11352979/a71341be-920d-11e5-94cf-eee468bde9a2.png)

When this happens, the Python script `server.py` is not affected (at least since the changes @jimhester and I have made).  When investigating the state of everything afterwards, it seems like there might be something about the R libraries or R executable causing the issue .  Here's content from the file `/Users/pkgbuild/packagebuilder/jobs/splineTCDiffExpr_20151123180252/installDeps.log` :

```
Loading required package: BiocInstaller
Bioconductor version 3.3 (BiocInstaller 1.21.2), ?biocLite for help
[1] "graph"
[1] "biocViews"
[1] "knitr"
[1] "knitrBootstrap"
[1] "BiocCheck"
trying URL 'https://bioconductor.org/packages/3.3/bioc/bin/macosx/mavericks/contrib/3.3/BiocCheck_1.7.0.tgz'
Content type 'unknown' length 4140908 bytes (3.9 MB)
==================================================
downloaded 3.9 MB


The downloaded binary packages are in
        /var/folders/s9/6yc1xdm13t3fl2dr3v5nmcqm0000gs/T//RtmpXwSPqS/downloaded_packages
[1] "devtools"
[1] "codetools"
[1] "httr"
Error in library(httr, lib.loc = bootstrap_libdir) : 
  there is no package called 'httr'
Execution halted

```

It could simply be that we need to install `httr` in the proper R LIB path, but is that the right solution ?

**Comment by b-long** [comment]
It's possible that something (a binary or source packages) for httr is missing from CRAN.  We should investigate that possibility.

**Comment by jimhester** [comment]
This should be fixed by 8cc458fb4d45473dcdb7be329909e04cee2400db, is that not being used?

**Comment by jimhester** [comment]
It also should not be installing _any_ binary packages for dependencies.

**Comment by b-long** [comment]
I believe it is being used, but I'll double-check in the morning.

**Comment by jimhester** [comment]
I have fixed this, see http://staging.bioconductor.org:8000/job/384/. Will open a pull request with my changes soon.
