### ISSUE TITLE
MiKTeX errors on moscato2

### ISSUE THREAD

**Issue by b-long** [Bioconductor/packagebuilder#2]
Errors on Moscato2, including : "_Windows API error 5: Access is denied._" (texi2pdf and framed.sty) .  This bug is blocking progress on a package currently under review.

```
* checking for file 'globalSeq/DESCRIPTION' ... OK
* preparing 'globalSeq':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"E:/packagebuilder/R/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
KPSEWH~1.EXE: Windows API error 5: Access is denied.
KPSEWH~1.EXE: Data: cprogramdatamiktex2.9miktexdatale1756f6ade37d5f870f23c05a7f81e257.fndb
Warning: running command 'kpsewhich framed.sty' had status 1
Warning in test_latex_pkg("framed", system.file("misc", "framed.sty", package = "knitr")) :
  unable to find LaTeX package 'framed'; will use a copy from knitr
Analysing a single chromosome.
Analysing multiple chromosomes:
chromosome 1
Analysing a single chromosome.
Analysing a single chromosome.
Warning: running command '"C:\progra~2\MiKTeX~1.9\miktex\bin\texi2dvi.exe" --quiet --pdf "globalSeq.tex" --max-iterations=20 -I "E:/packagebuilder/R/share/texmf/tex/latex" -I "E:/packagebuilder/R/share/texmf/bibtex/bst"' had status 1
Error in find_vignette_product(name, by = "texi2pdf", engine = engine) : 
  Failed to locate the 'texi2pdf' output file (by engine 'knitr::knitr') for vignette with name 'globalSeq'. The following files exist in directory '.': 'framed.sty', 'globalSeq-concordance.tex', 'globalSeq.R', 'globalSeq.Rnw', 'globalSeq.bib', 'globalSeq.tex'
Calls: <Anonymous> -> find_vignette_product
Execution halted
```

Tracker URL : https://tracker.bioconductor.org/issue1324
Failing build : http://bioconductor.org/spb_reports/globalSeq_0.99.4_buildreport_20151106035252.html#moscato2_buildsrc_anchor

cc/ @dtenenba @mtmorgan @jimhester @vobencha

**Comment by b-long** [comment]
So far, the only solution to this bug (per Dan), is rebooting Moscato2 and / or killing the instances of `pdflatex.exe` in task manager.  NB: To do that, you need to launch the task manager as the administrator.  Also note that you do not want to do this if the nightly builds are still running because there may be legitimate instances of `pdflatex.exe` doing work (creating vignettes, etc).  Unfortunately, this adds to our list of manual tasks managing the build servers.  We should try to resolve this soon.

**Comment by b-long** [comment]
@jimhester updated the MiKTeX packages today, so this problem should be resolved.  He was able to successfully build `rjags` and load it, which linked to JAGS 4.0.

I'll leave this open for now so that we can compare future build output and then confirm.

cc/ @vobencha @mtmorgan @hpages

**Comment by vobencha** [comment]
Thanks Jim!

**Comment by b-long** [comment]
It seems we are still experiencing problems related to MiKTeX on Moscato2 .  Consider [this recent build](http://staging.bioconductor.org:8000/job/387/#moscato2_buildsrc_anchor).  A snippet of the error output is below : 

```
* creating vignettes ...Warning: running command '"E:/packagebuilder/R/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR

### Removed text for brevity ...

Loading required package: splines
Loading required package: GeneNet
Loading required package: corpcor
Loading required package: longitudinal
Loading required package: fdrtool
Warning: running command '"C:\progra~2\MiKTeX~1.9\miktex\bin\texify.exe" --quiet --pdf "splineTCDiffExpr.tex" --max-iterations=20 -I "E:/packagebuilder/R/share/texmf/tex/latex" -I "E:/packagebuilder/R/share/texmf/bibtex/bst"' had status 5
Error in find_vignette_product(name, by = "texi2pdf", engine = engine) : 
  Failed to locate the 'texi2pdf' output file (by engine 'utils::Sweave') for vignette with name 'splineTCDiffExpr'. The following files exist in directory '.': 'degree_distribution.pdf', 'igraph_list.pdf', 'plots_df3_spline.pdf', 'scale_free_properties.pdf', 'single_igraph.pdf', 'splineTCDiffExpr-concordance.tex', 'splineTCDiffExpr.Rnw', 'splineTCDiffExpr.bib', 'splineTCDiffExpr.tex'
Calls: <Anonymous> -> find_vignette_product
Execution halted
```

**Comment by dtenenba** [comment]
Try running this same build again. Sometimes that's all it takes to fix this issue. Yes, not reproducible or explainable. It has been reported to R-core but they haven't done anything about it. 
OTOH sometimes it does happen consistently and then you need to investigate. 

Dan

**Comment by b-long** [comment]
Now re-executing the SPB for issue 1323 as per @dtenenba  : http://staging.bioconductor.org:8000/job/388/ .  I'll report back after Moscato2 finishes.

**Comment by b-long** [comment]
After re-executing the SPB for the above job, it appears to have failed in the same way.  See the build output: http://staging.bioconductor.org:8000/job/388/#moscato2_buildsrc_anchor .  The good news is, it's failed the same way, the bad news is the user who has submitted this package might be wondering why the tracker has notified them twice.  I think it might be useful to create a test package, registered to one of the team members to debug this problem further.

@vobencha Can you keep the package author updated via https://tracker.bioconductor.org/issue1323 ?

**Comment by b-long** [comment]
For future reference, here's error output related to LaTeX on Moscato2 from build reports generated today and yesterday : 

[GitHub - Bioconductor/packagebuilder/issues/2](https://drive.google.com/folderview?id=0BzoHffGHJ8WhNC1sVFpxNTcyM00&usp=sharing)

**Comment by vobencha** [comment]
@b-long Yes, I'll keep the authors of 1323 updated, thanks. @jimhester @mtmorgan  I'd like to approve a couple of packages that only fail the SPB on widows with this error. They'll fail on the windows builds until we fix this so status will remain 'pre-accepted'; somehow this seems better than letting them sit in the tracker. Thoughts?

**Comment by jimhester** [comment]
Setting them to pre-accepted sounds OK to me. I will add them to SVN, but wait to mark them 'accepted' until they build on windows.

**Comment by mtmorgan** [comment]
Setting to pre-accepted sounds better to me, too

**Comment by b-long** [comment]
:+1:

**Comment by b-long** [comment]
Fixed via: https://trello.com/c/CTaaRiWu/42-moscato2-miktex-triage
