### ISSUE TITLE
Consider migration to Amazon Simple Queue Service (SQS)

### ISSUE THREAD

**Issue by b-long** [Bioconductor/packagebuilder#20]
Creating an issue to track https://github.com/Bioconductor/packagebuilder/commit/eb963113f02b12d54278db1acec3c8e1738d0518

The documentation originally contained this proposal: 

> We may want to change the SPB to use Amazon Simple Queue Service (SQS) instead of ActiveMQ, then we would not pay for a broker machine to be up all the time, just for the individual messages we send.

**Comment by b-long** [comment]
I guess one thing that comes to mind about this proposal is, how would we then perform local development?  How much vendor lock-in might occur because of the change.  It does seem like many of the AWS services offer a big price savings, but we should investigate this fully.

**Comment by dtenenba** [comment]
Seems like you can abstract away the actual service used. So if there is a problem with SQS we could switch to an alternative. Here's a gist that mocks SQS for local (dev) usage:
https://gist.github.com/UnquietCode/5717942

**Comment by lshep** [comment]
Talked with Martin -  Currently Rabbitmq is working -  not fixing what isn't broke -  can revisit if need to update in the future
