### ISSUE TITLE
Replace '%s' in code

### ISSUE THREAD

**Issue by b-long** [Bioconductor/packagebuilder#22]
There are a lot of log statements like :

```
# value is substituted, by parameter order
logging.info("Some info about '%s'." % value)
```

It'd be more maintainable if we used this approach :

```
# value is substituted based on key
logging.info("Some info about '{hostname}'".format(hostname = value))
```

Many of these statements were made when https://github.com/Bioconductor/packagebuilder/pull/18 was merged, to find that bunch: `git diff eb96311..98cc540 --name-only | xargs grep -F '%s'`

**Comment by lshep** [comment]
Reviewed with Martin not planning on implementing in near future
