### ISSUE TITLE
Inconsistent configuration between zin2 and moscato2

### ISSUE THREAD

**Issue by b-long** [Bioconductor/packagebuilder#25]
I don't know if this is a bug or a feature, but wanted to open up the discussion.  I see that on zin2, the packagebuilder uses the following configuration : 

```
BBS_R_HOME=/home/biocbuild/bbs-3.3-bioc/R
```

Effectively, using the R environment (and library) that the main [BBS](https://github.com/bioconductor/BBS/) uses.  

**Conversely, moscato2 does not mirror this configuration**:

```
BBS_R_HOME=E:\packagebuilder\R
```

Is there a reason for the inconsistency?  If not, can we remove the added complexity?

Can anyone comment on this?

cc/ @vobencha @mtmorgan @jimhester @hpages @dtenenba

**Comment by dtenenba** [comment]
I don't remember the exact reason, but we needed to have a different R for packagebuilder on windows otherwise we ran into trouble.
Sorry, that's not super helpful. I'll see if I can track down more info.

**Comment by b-long** [comment]
Ok, no problem.  If it seems we need to make any changes (to any environment), let's just be careful to coordinate.  I'm actively working on zin2 and moscato2.
