### ISSUE TITLE
Tracking MikTex permissions issues and bug report

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/packagebuilder#32]
We need a place to track the MikTex permissions issue (described below). Since AFAICT MikTex does not have a formal bug tracker, I have reported the issue to the MikTex author via the contact page on his site. Here is the report. I will post any responses I get here.

Reported via: http://miktex.org/email

To: Christian Schenk

Subject: MikTex bug report - non-admin user needs to access c:\Users\Administrator

Hello,

Thank you for your work on MikTex. I would like to report a possible bug.

On a machine with Windows Server 2008 R2 Datacenter, I installed MikTex 2.9.5823. I installed it as Administrator and specified that I was installing for All Users, also answered Yes to installing missing packages on the fly.

Then as a non-admin user (called 'biocbuild') I ran the command:

```
kpsewhich framed.sty
```

I got this error:

```
C:\biocbuild\packagebuilder-master\test>kpsewhich framed.sty

======================================================================
starting package maintenance...
installation directory: "C:\Users\Administrator\AppData\Local\Programs\MiKTeX 2.
9"
package repository: http://ctan.mackichan.com/systems/win32/miktex/tm/packages/
visiting repository http://ctan.mackichan.com/systems/win32/miktex/tm/packages/.
..
repository type: remote package repository
loading lightweight database...
downloading http://ctan.mackichan.com/systems/win32/miktex/tm/packages/miktex-zz
db1-2.9.tar.lzma...
158506 bytes, 1311.79 KB/Sec

Unfortunately, the package framed could not be installed.Please check the log fi
le:
C:/Users/biocbuild/AppData/Local/MiKTeX/2.9/miktex/log/kpsewhich.log
======================================================================
```

Checking that log file, I see:

```
2015-12-21 23:10:18,762Z INFO  kpsewhich - installing package framed triggered by tex\latex\framed\framed.sty
2015-12-21 23:10:18,996Z INFO  kpsewhich - mpm: starting package maintenance...
2015-12-21 23:10:18,997Z INFO  kpsewhich - mpm: installation directory: "C:\Users\Administrator\AppData\Local\Programs\MiKTeX 2.9"
2015-12-21 23:10:18,997Z INFO  kpsewhich - mpm: package repository: http://ctan.mackichan.com/systems/win32/miktex/tm/packages/
2015-12-21 23:10:18,998Z INFO  kpsewhich - mpm: visiting repository http://ctan.mackichan.com/systems/win32/miktex/tm/packages/...
2015-12-21 23:10:18,998Z INFO  kpsewhich - mpm: repository type: remote package repository
2015-12-21 23:10:18,998Z INFO  kpsewhich - mpm: loading lightweight database...
2015-12-21 23:10:19,000Z INFO  kpsewhich - mpm: downloading http://ctan.mackichan.com/systems/win32/miktex/tm/packages/miktex-zzdb1-2.9.tar.lzma...
2015-12-21 23:10:19,132Z INFO  kpsewhich - mpm: 158506 bytes, 1311.79 KB/Sec
2015-12-21 23:10:19,145Z FATAL kpsewhich - Windows API error 5: Access is denied.

2015-12-21 23:10:19,145Z FATAL kpsewhich - Info: path="C:\Users\Administrator\AppData\Local\Programs"
2015-12-21 23:10:19,145Z FATAL kpsewhich - Source: Libraries\MiKTeX\Core\Directory\win\winDirectory.cpp
2015-12-21 23:10:19,145Z FATAL kpsewhich - Line: 74
```

It looks like in order for this command to succeed, my non-admin user has to have permission to access`c:\Users\Administrator` (or some directory underneath that) which of course it does not have by default, and probably should not have.

If I explicitly grant the `biocbuild` user access to that directory (by navigating to the directory in Explorer, right-clicking it, and choosing Security, then adding HOSTNAME\biocbuild and giving it Full Control) ,  the above `kpsewhich` command succeeds. 

However, I should not have to do that.

If I uninstall MikTex and reinstall it as `biocbuild`, specifying to use it just for `biocbuild`, everything works fine. But I prefer to have a single global install because I want all users to be able to use it.

Is this a bug? If so, can it be fixed?
Is there another place I should report this?

Thanks,
Dan

**Comment by dtenenba** [comment]
It turns out there is a bug tracker and I have posted this bug there:
https://sourceforge.net/p/miktex/bugs/2422/
So maybe we don't need this issue. But I'll leave it here for now.
There is also a mailing list at: http://miktex.org/list

BTW, although there is a bug tracker at sourceforge, there is no source code there.
It is unclear where the source code is available, if it is in fact available.
Brian raised this point and we may want to consider it over the long term: it appears that MikTex is a one-person operation. As such we run the risk of suffering from the open-source form of vendor lock-in if this developer is hit by a bus or loses interest in the project.
In any case we may want to investigate alternatives to MikTex. From preliminary googling it seems that TexLive is the main alternative: https://www.tug.org/texlive/windows.html
Without making any statements as to which one is better (because I really don't know) it does appear that TexLive is distributed by the Tex Users Group (tug.org) which means many more people are involved in maintaining it. Additionally it's easy to find the source code.

Just something to think about.
@b-long @mtmorgan @priscian

**Comment by dtenenba** [comment]
A response at http://sourceforge.net/p/miktex/bugs/2422/#9ed3 

"Thank you. I will fix this by a implementing a better default value for the installation directory (e.g., C:\Program Files\MiKTeX 2.9)."

**Comment by dtenenba** [comment]
FYI, a major update of MikTex is on the way, they recommend not updating immediately in a production environment:
http://miktex.org/announcement/miktex-2-9-5800

**Comment by lshep** [comment]
I believe this is resolved.
