### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by b-long** [Bioconductor/packagebuilder#34]
Need to modify https://github.com/Bioconductor/packagebuilder/blob/master/documentation/Deployment.md and add the following deployment instructions : 

```
git clone https://github.com/Bioconductor/packagebuilder.git
cd packagebuilder

# New stuff
virtualenv env
pip install -r PIP-DEPENDENCIES--packagebuilder.txt
```

Lastly, modify [workers/static-config.sh#L44-L45](https://github.com/Bioconductor/packagebuilder/blob/01232ce9c26abee94a23c3cab5ef05ca68f342c6/workers/static-config.sh#L44-L45_) appropriately.

**Comment by lshep** [comment]
This has been updated with new documentation
