### ISSUE TITLE
server.py stops responding after first message

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/packagebuilder#35]
(initially misfiled in BBS)

So as we know the SPB has been unstable and my theory was that if the activemq broker stops, everything that listens (server.py, archiver.py, track_build_completion.py) needs to be restarted.

That may be true but it is not the whole story.
This morning the spb was unresponsive again and the broker had not gone down.

I was able to reproduce/observe the problem as follows:

On staging as biocadmin, kick off a build of a test package:

```
cd packagebuilder
source env/bin/activate
python rerun_build.py 558 https://tracker.bioconductor.org/file6458/spbtest_0.99.0.tar.gz
```

While on one of the build nodes, say pkgbuild@zin2, observing the server log:

```
cd packagebuilder
tail -f server.log
```

You can see that it does not indicate receipt of the message.
If you stop and restart the server, and then kick off the build again, it will display receipt of the message the first time you kick off a test build but not subsequent times.

In the course of investigating this, I stumbled upon the fact that it has to do with using the shell script `run-build-server.sh`  to start the server.
If you instead just paste these commands into the shell, the script works, and responds to/acknowledges/processes messages:

```
source env/bin/activate
. workers/static-config.sh
nohup python -m workers.server > server.log 2>&1 &
```

That fixes things on Linux and Mac (I'm not sure why)  but the same is not true on Windows.

If I paste all the following into a command window on moscato2 (logged in as dtenenba):

```
call env\Scripts\activate.bat

set BBS_PYTHON_CMD=C:\Python27\python.exe
set BBS_RSYNC_CMD=C:\cygwin\bin\rsync.exe

@rem With StrictHostKeyChecking=no, ssh will automatically add new host keys
@rem to the user known hosts files (so it doesn't get stalled waiting for an
@rem answer when not run interactively).
set BBS_SSH_CMD=%BBS_SSH_CMD% -qi %BBS_RSAKEY% -o StrictHostKeyChecking=no
set BBS_RSYNC_CMD=%BBS_RSYNC_CMD% -r --delete --exclude='.svn'
set BBS_RSYNC_RSH_CMD=%BBS_RSYNC_CMD% -e '%BBS_SSH_CMD%'
set BBS_CENTRAL_BASEURL=http://zin2/BBS/%BBS_BIOC_VERSIONED_REPO_PATH%
python -m workers.server > server.log 2>&1
```

The server that runs only responds the first time a test build is kicked off, not to subsequent kickoffs. 

So...I have temporarily removed moscato2 from the spb builds until we can figure this out.
Meanwhile I have restarted a bunch of builds that @vobencha asked me to do. If anyone else needs any builds kicked off, let me know. They will not have windows builds but it's better than nothing I guess.

Note also that on moscato2 I have changed the spb from a service to a scheduled task that starts at startup. This seems a lot easier to manage. But it's currently a work in progress because of the above issue. 

If I make any further discoveries about this issue I will share them here.

@b-long @mtmorgan @hpages @priscian

**Comment by dtenenba** [comment]
It seems that the above is still not the whole story. Even after starting the server in the manner described above, sometimes it stops receiving messages. Investigating further.

**Comment by dtenenba** [comment]
One annoying this is that I cannot reproduce this with the local dev setup (https://github.com/Bioconductor/packagebuilder/blob/master/documentation/Developing.md) . It only seems to happen in the live production configuration.

**Comment by dtenenba** [comment]
OK, update. 

My next theory was that server.py, after servicing that initial message, gets into some state where it fails to see subsequent messages. I created a fork, the misnamed (or misnumbered) https://github.com/Bioconductor/packagebuilder/tree/feature/debug_issue_52 in which on_message() dispatches the bulk of its work to the `do_work()` function, run in a new thread. This **seems** to fix the issue though as we have learned it is probably too soon to say. 

At any rate, I have checked out the build nodes to that branch and if it continues to work we can merge it.

The same change might need to be made to the other code that listens for messages (archiver.py and track_build_completion.py).

I guess I will leave this issue open for now. I'll close it after it's merged into master if that's what ends up happening.

**Comment by dtenenba** [comment]
Another update. Forgot to clarify before that windows is working again; the threading fix described above took care of it.

Also, it appeared to be necessary to update track_build_completion.py in the same way. I did so in the branch https://github.com/Bioconductor/spb_history/tree/feature/server_dispatch_to_thread . However, the working copy of spb_history on staging is checked out to a local-only branch called changes-on-staging, and I am not able to merge, so I just manually pasted the new contents of track_build_completion.py. We can resolve this in a less messy way on Monday.

So my theory overall is that after switching to the stomp.py library (which behaves fairly differently to the old stomp library--whereas the old one was single-threaded, the new one calls the callback in a different thread) the listeners always or at least often went into a non-responsive state after the first message.  It seems that having the on_message() method of the listener dispatch to  a new thread fixes this. It hasn't proved to be necessary for archiver,py (at least not yet) and I am not sure why.

OK, we'll see if this thing stays up over the weekend.

**Comment by b-long** [comment]
Hi Dan, I think we should discuss a few points.  You stated in your [first comment](https://github.com/Bioconductor/packagebuilder/issues/35#issue-125731685) : 

> [the problem] has to do with using the shell script `run-build-server.sh` to start the server.
> If you instead just paste these commands into the shell, the script works, and responds to/acknowledges/processes messages:

Is this still true or have you found any other information about that shell script ? 

Also, in the [previous comment](https://github.com/Bioconductor/packagebuilder/issues/35#issuecomment-170185542), you point out : 

>  However, the working copy of spb_history on staging is checked out to a local-only branch called changes-on-staging

Yes, that is my fault.  We need to devise a deployment strategy that takes into account development vs. production properties.  Since production properties can include sensitive information, we can't store those sensitive values in GitHub.  One idea to solve this problem is as follows : (1) use the non-public repository [Bioconductor/private](https://github.com/Bioconductor/private) to store these sensitive values, (2) clone a copy of `Bioconductor/private` to **every** production build node (e.g. in *nix environments at `/etc/syconfig/bioconductor`) , (3) and modify the common [`config.py`](https://github.com/Bioconductor/bioc-common-python/blob/b4d777241b93fcc1beecd4113fea349292c8a549/bioconductor/config.py) to load sensitive values from such a location _when the environment (mode) is set to production_.  This would allow us to keep the [version-controlled environment always set to production](https://github.com/Bioconductor/spb_history/blob/f85899f329eef7b68662f98e8da4888d7bb51483/bioconductor.properties#L4), and the "dirty" part  could be flipping the mode to "development" when working locally or in an environment like TravisCI. 

cc/ @mtmorgan @vobencha @priscian

**Comment by b-long** [comment]
One thing that might be worth considering (and would presumably require [little effort](https://github.com/Bioconductor/bioc-common-python/blob/b4d777241b93fcc1beecd4113fea349292c8a549/PIP-DEPENDENCIES--bioc-common-python.txt#L20)), is upgrading from `stomp.py v. 4.1.8` to `stomp.py v. 4.1.9` (released about a week ago).  Many of the [changes in 4.1.9](https://github.com/jasonrbriggs/stomp.py/blob/163637359dcea0ddae8c202beb79cf4f128bbf40/CHANGELOG#L1-L14) target ActiveMQ, and perhaps upgrading the Stomp client would resolve some of the issues we've seen.

**Comment by dtenenba** [comment]
Done.

**Comment by b-long** [comment]
_Whoa!_ @dtenenba , I thought you were on vacation today :smile: Have you deployed these changes as well or should we add that to the backlog?

**Comment by dtenenba** [comment]
Deployed. Updated PIP-dependencies-\* and deployed those to staging + build nodes, plus updated to stomp.py 4.1.9. Leaving later today. ;)

**Comment by b-long** [comment]
Awesome, thanks @dtenenba !  We'll have to wait and see how this affects stability.

**Comment by dtenenba** [comment]
Forgot to mention that I also restarted all listeners so they are actually running the new version of stomp.py.

**Comment by lshep** [comment]
I believe this is resolved.  While occasionally we still run into a random period where listeners are not responding and have to be restarted this is now generally rare (and I think related to system updates and reboots at RPCI) . The SPB generally stays on and connected for the majority of the time.
