### ISSUE TITLE
Misleading use of "Bioconductor Build System" where supposedly "Single Package Builder" is meant

### ISSUE THREAD

**Issue by hpages** [Bioconductor/packagebuilder#41]
@lshep Not sure if this is the right place to report this. Let me know if I should report this somewhere else.

To disambiguate, avoid confusion, and use consistent terminology, could we use "Single Package Builder" instead of "Bioconductor Build System" in the following automatic message from bioc-issue-bot:

> The following are build products from R CMD build on the Bioconductor Build
> System:

An example of such message can be found [here](https://github.com/Bioconductor/Contributions/issues/3226#issuecomment-1792733033).

Not sure where the code that generates those messages lives but if you point me in the right direction I could try to prepare a PR.

Thanks!

**Comment by lshep** [comment]
I don't necessarily think its misleading -  we use the same R and the same library as the BBS and same system wide dependencies which is why I thought it was appropriate -  the only difference is a separate additional library location for dependencies not yet installed for the currently available packages in case it doesn't get accepted.

**Comment by hpages** [comment]
Sure they share a few things but they are different build systems with important differences. All I'm saying is that during the submission process the submitter interacts with the SPB, not with the BBS. They only get moved from the SPB to the BBS once they are accepted. I think keeping a clear distinction between the 2 systems helps submitters understand the process and avoids possible confusion.

**Comment by lshep** [comment]
fair enough.  I can make the change.  Its actually here: https://github.com/Bioconductor/spb_history/blob/UpdateVersions/track_build_completion.py#L110 .  I'm updating scripts for the change over to Bioc 3.19 so I can do it then.  I want to try to clean up the branches too.  The active branch is currently the UpdateVersions branch cause I never merged over.

**Comment by lshep** [comment]
https://github.com/Bioconductor/spb_history/commit/55d94f14fe3868ed068556500875aa1261646241

**Comment by hpages** [comment]
Thanks!
